export type TDonation = {
  _id?: string;
  name: string;
  mobile_number: string;
  email: string;
  donation_country: string;
  address: string;
  donation_purpose: string;
  donation_amount: number;
  payment_method?: string;
  bank_account_no?: string;
  check_no?: string;
  card_number?: string;
  card_holder_name?: string;
  card_transaction_no?: string;
  card_type?: string;
  month_first?: string;
  month_second?: string;
  year?: string;
  security_code?: string;
  referenceNo?: string;
  transactionId: string;
  transaction_no: string;
  description?: string;
  createdAt?: string;
  updatedAt?: string;
  __v?: number;
};
